### ISSUE TITLE
Decrease build time by parallelizing documentation and integration tests

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#1342]
## Situation
With 
- #1340 

we have already improved the execution time of our builds by making the integration tests much more faster. But there is still a need to make the complete build faster.

## Wanted
The documentation build and the integration tests shall run parallel.
The build process should look like
```
                                            START
               -------------------------------V------------------------------
                                 Build (go) client
                                 Build SecHub Server + API      
                                             ...                            
               -------------------------------V------------------------------
                         Execute only documentation integration tests (A)
                                              V
                 Build documentation (B)      |   Execute integration tests
               -------------------------------V------------------------------
                                             END

```

### General: separation of integration tests
Inside #1340 two system properties:
- `sechub.integrationtest.only.necessary4documentation`
- `sechub.integrationtest.never.necessary4documentation`
were introduced. 

With this system properties it is possible to handle `(A)` and `(B)` separately as shown in former figure.

### Build Server approach (Variant A)
Here we must differ between our Jenkins and the GitHub actions build:
1. Jenkins
Just do it parallel - should be easy.

2. Github Actions
Find a way to parallelize - open

```yaml
name: parallel-jobs
on:
  push:
jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing work"
  job-b:
    runs-on: ubuntu-latest
    steps:
      - run: echo "More work at the same time"

```
The problem here is, that the jobs are isolated (will run in different pods/docker containers etc.). 
But when we have already the build artifacts they are accessible and... we can download them inside the other job.
In our case for documentation, we would additionally add the test output from documentation integration tests into a zip file (just some text information, very small), so they are available.

With "needs other job" + reuse of other job output we could do it:
```yaml
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}

```

More details at
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs

### Gradle approach (Variant B)
If variant A is not possible, we could still parallelize the process in our gradle build  - but .. I am not sure if this 
would really decrease build time a lot?
