### ISSUE TITLE
pds solutions: workspace folder not writeable for pds user

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1761]
## Problem
The `/workspace` folder belongs to root when mounted as ephemeral storage.
These setups cannot execute scans.

## Solution
Set security context for all pds solutions like this in the deployment.yaml files:
```
            securityContext:
                runAsUser: 2323 # user id of the application user. (overrides settings in the Dockerfile)
                runAsGroup: 2323 # group id of the application group. (overrides setings in the Dockerfile)
                fsGroup: 2323 # group id of the application group. Set in the Dockerfile. This group has write access to the volumes.
```
