### ISSUE TITLE
PDS-solutions: Lower number of permanent database connections

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1822]
## Problem
PDS uses the Hikari connection pool manager which defaults to 10 permanent db connections.
When running a couple of PDS, the connection limit of the database can be easily reached. (PostgreSQL defaults to 100 connections)

With PostgreSQL, the error message is:
```
psql: error: FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

## Solution
Since the PDS uses the database only for persisting status changes and sync between the cluster members, one connection per PDS should be sufficient. The connection is only used for milliseconds.
(-> do some tests to determine if pinning to one db connection is sufficient or if the max. should be set to two connections)

These environment variables must be set in the container's deployment yaml: (-> Helm chart template)
```yaml
        - name: SPRING_DATASOURCE_HIKARI_MINIMUMIDLE
          value: "1"
        - name: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
          value: "2"
```
