### ISSUE TITLE
pds-solutions: Make container memory configurable

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#2067]
## ToDo:
Make container memory configurable in Helm charts of all pds-solutions. (some have this setting already)
Example:
```yaml
resources:
    requests:
        memory: 512Mi
    limits:
        memory: 6Gi
```
