### ISSUE TITLE
pds-solutions: Make worker thread count configurable

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#2068]
## ToDo:
Make
- worker thread count
- maximum queue size
configurable in Helm charts of all pds-solutions. (some have this setting already)

Example:
```yaml
pds:
    config:
        execute:
            queueMax: 10
            workerThreadCount: 5
```
