### ISSUE TITLE
PDS: limit db connections per default

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#2406]
## Situation
Currently when a PDS is started, the Hikari database connection pool will create 10 database connections.
1-2 shared pool connections are sufficient for a PDS.
Additionally: with many PDS solutions, you can easily reach the max connection limit of the databasee.

So in the Helm chart of every PDS solution, we have set this:
```yaml
            # limit database connection pool
            - name: SPRING_DATASOURCE_HIKARI_MINIMUMIDLE
              value: "1"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE
              value: "2"
```

## Wanted
Set the default in the PDS Spring profile like above.
