### ISSUE TITLE
pds-cloc: runAs needs to be added to Helm chart

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#2407]
## Situation
The PDS user has no privileges to write into `/workspace` directory.

## ToDo
Add this to Helm's deployment.yaml file:
```yaml
      securityContext:
        runAsUser: 2323 # user id of the application user. (overrides settings in the Dockerfile)
        runAsGroup: 2323 # group id of the application group. (overrides setings in the Dockerfile)
        fsGroup: 2323 # group id of the application group. Set in the Dockerfile. This group has write access to the volumes.
```
