### ISSUE TITLE
Extend the sechub github scan action with a parameter for scan types

### ISSUE THREAD

**Issue by winzj** [mercedes-benz/sechub#2441]
### Situation
The Sechub scan Github action allows different parameters to create a sechub.json configuration file during the workflow. Currently there is no value that allows specifying `scan types`. The action would always default to `codeScan` in that case.

### Wanted
We want to introduce a parameter called `scan-types` that contains a comma separated list of scan types which shall be performed.
```yaml
- uses: mercedes-benz/sechub/github-actions/scan@72a27282da80952e6fadcef452c6a9085971c688
  with:
    # OPTIONAL: A list of scan types that shall be executed
    scan-types: codeScan, secretScan
```
If the Github scan action still uses the old way to perform the `codeScan`, this must be updated, so the new way with data sections and references is used.
Before implementing this issue, please have a look  if #2438 was already fixed.
