### ISSUE TITLE
Introduce gradle caching for all actions workflows

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#2677]
## Situation
As experienced lately: Not in all cases the gradle caching works.
Then on every run, the gradle archive is being downloaded and extracted.
Snippet (`cache: gradle` does not work in every case):
```yaml
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
```

## ToDo
Change above to use `gradle-build-action` for caching:
```yaml
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
```
