### ISSUE TITLE
Make actions workflows for release work with CLA restrictions

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#2678]
## Situation
Lately, on this repo the CLA bot has been activated. It enforces signing the CLA for each contributor before PRs are accepted.

Unfortunately, in our release workflows we create PRs with a fake email address:
```yaml
          git config user.name "SecHub release job (github-actions)"
          git config user.email github-actions-sechub@users.noreply.github.com
```

## Wanted
Make our release workflows work again

## Solution
Query the caller's email address and use it instead of the fake one in the git commit.
It could look like this:
```yaml
on:
  workflow_dispatch:
    inputs:
      actor-email:
        description: Insert your email address here. It will be used in generated pull requests
...
        run: |
          git config user.name "$GITHUB_TRIGGERING_ACTOR (via github-actions)"
          git config user.email "${{ inputs.actor-email }}"
```
