### ISSUE TITLE
Server Helm Chart: Add pdsIaC section to values.yaml

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#2815]
## Situation
Although `pdsIaC` is contained in the templates, it is missing in the `values.yaml` file of the Helm chart.
It must be added in order to reveal that such a PDS exists.

## ToDo
Add section to `values.yaml` file:
```yaml
# ------------------------------------------------------------------------------------- #
# PDS-IaC adapter
# ------------------------------------------------------------------------------------- #
pdsIaC:
  enabled: false
  # Put the user id  of PDS-IaC in k8s secret secret-pds-iac:techuser_username
  # Put the password of PDS-IaC in k8s secret secret-pds-iac:techuser_password
```
