### ISSUE TITLE
GitHub Actions build fails

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#2831]
## Situation
When triggering 
https://github.com/mercedes-benz/sechub/actions/workflows/github-action-scan.yml

![image](https://github.com/mercedes-benz/sechub/assets/11644753/bc79350c-2cf6-480e-8ff5-d434adb32ab0)
happens on `develop` branch but also in `feature-2441-provide-multiple-scan-types` (current development) 

## Wanted
Build shall work again.

**Comment by de-jcup** [comment]
With initial commit 
https://github.com/mercedes-benz/sechub/commit/51be628a6ead01bc7a02a896833622aee364196c

the build was working... But it seems there were changes in the meanwhile at github actions side.

There are discussions about the usage of "working-directory" inside the actions:
https://github.com/orgs/community/discussions/25742

I think 
https://github.com/orgs/community/discussions/25742#discussioncomment-5659259
sound interesting - the proposal is here:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shared-models
```
