### ISSUE TITLE
SecHub Server Helm chart: make env vars configurable

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#3042]
## Situation
Currently there is no option to set environment variables for containers directly.
Instead there is a construct like this in the deployment.yaml:
```yaml
{{- if .Values.pdsGoSec.enabled }}
# ----------------------------------------------------------------------------------------------#
# - Scope: PDS-GoSec
# --------------------------------------------------------------------------------------------- #
        - name: SECHUB_PDS_GOSEC_USERID
          valueFrom:
            secretKeyRef:
               name: secret-pds-gosec
               key: techuser_username
        - name: SECHUB_PDS_GOSEC_PASSWORD
          valueFrom:
            secretKeyRef:
               name: secret-pds-gosec
               key: techuser_password
{{- end }}
```
If someone creates their own PDS solution and wants to set the secrets via environment variables, then currently this is not possible.

## Wanted
A possibility to define envrionment variables directly via the values.yaml

## Solution
Change the Helm chart so it's possible to define environment vars directly in the values.yaml.
Remove the `{{- if .Values.pdsXYZ.enabled }}` construct.
