### ISSUE TITLE
Server Helm Chart: add section for `security`

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#3779]
## Situation
There are a bunch of new variables introduced since the web-server functionality has been added to SecHub server:
```yaml
  security:
    server:
      modes:
        - oauth2
        - classic
      oauth2:
        mode: jwt
        jwt:
          jwk-set-uri: http://localhost:8080/realms/local-realm/protocol/openid-connect/certs
        opaque-token:
          client-id: my-client-id
          client-secret: ...
          introspection-uri: http://localhost:8080/introspect.oauth2
    login:
      enabled: true
      login-page: /login
      redirect-uri: https://www.google.com
      modes:
        - oauth2
        - classic
      oauth2:
        client-id: web-ui-server-local
        client-secret: ...
        provider: keycloak
        redirect-uri: https://localhost:8443/login/oauth2/code/keycloak
        issuer-uri: http://localhost:8080/realms/local-realm
        authorization-uri: http://localhost:8080/realms/local-realm/protocol/openid-connect/auth
        token-uri: http://localhost:8080/realms/local-realm/protocol/openid-connect/token
        user-info-uri: http://localhost:8080/realms/local-realm/protocol/openid-connect/userinfo
        jwk-set-uri: http://localhost:8080/realms/local-realm/protocol/openid-connect/certs
    encryption:
      secret-key: ...
```

## ToDo
* Add the new attributes to the server's Helm chart in `values.yaml` and set the environment variables in the container accordingly
* add explaining comments to the new attributes
* remove the old `oauth2` section which is no longer needed
