### ISSUE TITLE
Docker-Compose example for instant run of SecHub Server, PDS, and Databases locally

### ISSUE THREAD

**Issue by 4w31ss3** [mercedes-benz/sechub#612]
## Proposal

We could offer a `docker-compose.yml` example file that allows to start everything necessary to run, develop and debug SecHub locally.

The example code could be placed in a subfolder `examples`: 
```
- sechub
    - examples
    - ...
```

The corresponding docker-compose.yml could look like this:

```
version: "3.9"

services:
    sechub-server:
        build:
            context: ../
            dockerfile: ./examples/sechub-server.dockerfile
        ports:
            - "8443:8443"
        profiles: ["full", "sechub-server", "pds"]
        networks:
            - sechub
            - pds

    sechub-db:
        image: postgres
        profiles: ["full", "sechub-server"]
        networks:
            - sechub
            
# ---------------------------------------------------------------------
# -------------------------------- PDS --------------------------------
# ---------------------------------------------------------------------

    pds:
        build:
            context: ../
            dockerfile: ./examples/pds.dockerfile
        ports:
            - "8444:8444"
        profiles: ["full", "pds"]
        networks:
            - pds
    
    pds-db:
        image: postgres
        profiles: ["full", "pds"]
        networks:
            - pds

networks:
    sechub:
    pds:
```

Starting only SecHub-server with a database could be done like this:
`docker compose --profile sechub-server up --build`
or with all components
`docker compose --profile full up --build`
